---
- name: Ensure root password is set (Darwin)
  include_tasks: from_initial/blank.yml
  when: mysql_initial_root_password_blank

- name: Ensure root password is reset (Darwin)
  include_tasks: from_initial/random.yml
  when: not mysql_initial_root_password_blank
