---
- name: Ensure MySQL service is stopped (Debian)
  service:
    name: '{{ mysql_service_name }}'
    state: stopped
  become: true

- name: Ensure MySQL service is started (Debian)
  service:
    name: '{{ mysql_service_name }}'
    state: started
    enabled: true
  become: true
