---
- name: Check authentication plugin for MySQL root user (Unix)
  shell: "{{ mysql_executable_path }}/mysql \
    -s -N -u root -p'{{ mysql_root_password }}' \
    -e 'SELECT plugin FROM mysql.user WHERE user = \"root\";'"
  register: query_result
  changed_when: false

- block:

  - name: Set temporary password policy level (Unix)
    shell: "mysql -u root -p'{{ mysql_root_password }}' -e 'SET GLOBAL {{ item }};'"
    loop:
      "{{ mysql_password_policy_settings[mysql_version_parts['major']|string]|flatten(levels=1) }}"
    when: |-
      mysql_password_policy_settings is defined and
      mysql_allow_simple_passwords

  - name: Set authentication plugin type for MySQL root user (Unix)
    shell: "{{ mysql_executable_path }}/mysql \
      -s -N -u root -p'{{ mysql_root_password }}' \
      -e 'ALTER USER root@localhost IDENTIFIED WITH \
      {{ mysql_authentication_plugin }} BY \"{{ mysql_root_password }}\";'"

  when: query_result.stdout != mysql_authentication_plugin
