- name: Create MySQL databases (Windows)
  win_command: "\"{{ mysql_executable_path }}\\mysql.exe\" -u root \
    -p{{ mysql_root_password }} -e \"CREATE DATABASE IF NOT EXISTS {{ item }};\""
  loop: "{{ mysql_databases }}"
  changed_when: false
