---
- name: Ensure MySQL Installer Console is installed (Windows)
  win_package:
    path: '{{ mysql_installers_path_on_target }}\{{ mysql_installer_filename }}'
    creates_path: 'C:\Program Files (x86)\MySQL\MySQL Installer for Windows'
    state: present

- name: Ensure MySQL instance is installed (Windows)
  win_shell: |
    $mySqlInstallerConsole = "C:\Program Files (x86)\MySQL\MySQL Installer for Windows\MySQLInstallerConsole.exe"
    $mySqlOptions = "server;{{ mysql_version_string }};x64:*:type=config;openfirewall=true;generallog=true;binlog=true;enable_tcpip=true;rootpasswd={{ mysql_root_password }}"
    Start-Process -FilePath $mySqlInstallerConsole -ArgumentList community, install, -silent, "$mySqlOptions" -Wait -NoNewWindow

- name: Ensure MySQL executable is added to PATH (Windows)
  win_shell: |
    $theCurrentPath=(Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH).Path
    $theUpdatedPath=$theCurrentPath+';{{ mysql_executable_path }}'
    Set-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH –Value $theUpdatedPath
